<x-layouts.tailwind-app title="Pengaturan Sekolah">
    <div class="space-y-6">
        <x-page-header title="Pengaturan Sekolah" subtitle="Atur data sekolah dan dokumen SPJ." kicker="PENGATURAN">
            <div class="grid divide-y divide-[var(--ui-line)] sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4"><x-stat-item label="Sekolah aktif" :value="$activeSchool?->name ?? 'Belum dipilih'" hint="Konteks kerja" /><x-stat-item label="Tahun aktif" :value="$activeYear?->year ?? '—'" :hint="$activeYear?->fund_source ?? 'Belum dipilih'" /><x-stat-item label="Jumlah sekolah" :value="$schools->count()" hint="Dalam akses Anda" /><x-stat-item label="Kode sekolah" :value="$activeSchool?->school_code ?: '—'" hint="Untuk nomor dokumen" /></div>
        </x-page-header>
        @if(session('success'))<x-ui.alert variant="success">{{ session('success') }}</x-ui.alert>@endif
        @if(session('error'))<x-ui.alert variant="danger">{{ session('error') }}</x-ui.alert>@endif
        @if($errors->any())<x-ui.alert variant="danger">{{ $errors->first() }}</x-ui.alert>@endif
        <style>
            @media (min-width: 1024px) { form[action*="pengaturan/sekolah/profil"] { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:.75rem } form[action*="pengaturan/sekolah/profil"] > div:last-child { grid-column:1/-1 } }
            form[action*="pengaturan/sekolah/profil"] .ui-form-section-header, form[action*="pengaturan/sekolah/profil"] .ui-form-section-body { padding:.8rem 1rem }
        </style>
        <section class="space-y-6">
            @if($activeSchool)
                <form method="POST" action="{{ route('schools.profile.update') }}" enctype="multipart/form-data" class="space-y-6">@csrf @method('PUT')
                    <x-ui.form-section title="Identitas dan Alamat Sekolah" description="Data utama sekolah."><div class="grid gap-3 md:grid-cols-2"><x-ui.field label="Kode sekolah" required><x-ui.input name="school_code" :value="old('school_code',$activeSchool->school_code)" maxlength="40" required /></x-ui.field><x-ui.field label="NPSN" required><x-ui.input name="npsn" :value="old('npsn',$activeSchool->npsn)" required /></x-ui.field><x-ui.field label="Nama sekolah" class="md:col-span-2" required><x-ui.input name="name" :value="old('name',$activeSchool->name)" required /></x-ui.field><x-ui.field label="Alamat"><x-ui.input name="address" :value="old('address',$activeSchool->address)" /></x-ui.field><x-ui.field label="Desa/Kelurahan"><x-ui.input name="desa" :value="old('desa',$activeSchool->desa)" /></x-ui.field><x-ui.field label="Kecamatan"><x-ui.input name="district" :value="old('district',$activeSchool->district)" /></x-ui.field><x-ui.field label="Kabupaten/Kota"><x-ui.input name="regency" :value="old('regency',$activeSchool->regency)" /></x-ui.field><x-ui.field label="Provinsi"><x-ui.input name="province" :value="old('province',$activeSchool->province)" /></x-ui.field></div></x-ui.form-section>
                    <x-ui.form-section title="Penandatangan Dokumen" description="Data yang dicetak pada dokumen."><div class="grid gap-3 md:grid-cols-2">@foreach(['principal_name'=>'Nama kepala sekolah','principal_nip'=>'NIP kepala sekolah','principal_email'=>'Email kepala sekolah','principal_phone'=>'Telepon kepala sekolah','treasurer_name'=>'Nama bendahara','treasurer_nip'=>'NIP bendahara','treasurer_email'=>'Email bendahara','treasurer_phone'=>'Telepon bendahara','inventory_manager_name'=>'Nama Pengurus Barang','inventory_manager_nip'=>'NIP Pengurus Barang'] as $field=>$label)<x-ui.field :label="$label"><x-ui.input :type="str_contains($field,'email')?'email':'text'" :name="$field" :value="old($field,data_get($profile,$field,''))" /></x-ui.field>@endforeach</div></x-ui.form-section>
                    <x-ui.form-section title="Kop Surat" description="Unggah gambar kop surat."><div class="flex flex-wrap items-center gap-4"><x-ui.field label="File kop surat"><input type="file" name="letterhead" accept="image/png,image/jpeg" class="block text-sm" /></x-ui.field>@if($activeSchool->letterhead_path)<img src="{{ route('schools.letterhead',['v'=>$activeSchool->updated_at?->timestamp]) }}" alt="Kop surat" class="h-16 max-w-xs rounded border object-contain">@endif</div></x-ui.form-section>
                    <x-ui.form-section title="Penyimpanan Dokumen Global" description="Folder tujuan salinan dokumen."><x-ui.field label="Path folder dokumen" for="document_storage_path" :error="$errors->first('document_storage_path')"><x-ui.input id="document_storage_path" name="document_storage_path" :value="old('document_storage_path',$documentStoragePath??'')" placeholder="D:\Dokumen-SPJ" required /></x-ui.field></x-ui.form-section>
                    <div class="flex justify-end"><x-ui.button type="submit">Simpan Semua Perubahan</x-ui.button></div>
                </form>
            @else<x-ui.alert variant="warning">Pilih sekolah aktif terlebih dahulu.</x-ui.alert>@endif

            @if(auth()->user()->isAdministrator())
                <details class="rounded-2xl border border-[var(--ui-line)] bg-[var(--ui-surface-base)] shadow-sm" open><summary class="cursor-pointer px-5 py-4 font-bold text-[var(--ui-fg-strong)]">Administrasi Administrator</summary><div class="grid gap-6 border-t border-[var(--ui-line)] p-5 xl:grid-cols-2"><div class="space-y-6"><x-ui.form-section title="Tambah Tahun Anggaran" description="Tambahkan tahun dan sumber dana."><form method="POST" action="{{ route('years.store') }}" class="space-y-4">@csrf<x-ui.field label="Sekolah" required><x-ui.select name="school_id" required>@foreach($schools as $school)<option value="{{ $school->id }}">{{ $school->name }}</option>@endforeach</x-ui.select></x-ui.field><div class="grid gap-4 sm:grid-cols-2"><x-ui.field label="Tahun" required><x-ui.input type="number" name="year" :value="date('Y')" min="2020" max="2100" required /></x-ui.field><x-ui.field label="Sumber dana" required><x-ui.select name="fund_source_id" required>@foreach($fundSources as $source)<option value="{{ $source->id }}">{{ $source->code }} · {{ $source->name }}</option>@endforeach</x-ui.select></x-ui.field></div><x-ui.button type="submit">Tambah Tahun</x-ui.button></form></x-ui.form-section><x-ui.form-section title="Tambah Sekolah Baru" description="Daftarkan sekolah dan database operasionalnya."><form method="POST" action="{{ route('schools.store') }}" class="space-y-4"><div class="grid gap-4 sm:grid-cols-2">@csrf<x-ui.field label="Kode sekolah" required><x-ui.input name="school_code" required /></x-ui.field><x-ui.field label="NPSN" required><x-ui.input name="npsn" required /></x-ui.field><x-ui.field label="Nama sekolah" class="sm:col-span-2" required><x-ui.input name="name" required /></x-ui.field></div><x-ui.button type="submit">Tambah Sekolah</x-ui.button></form></x-ui.form-section></div><x-ui.form-section title="Master Sekolah" description="Daftar sekolah yang terdaftar."><livewire:school-master /></x-ui.form-section></div></details>
            @endif
        </section>
    </div>
</x-layouts.tailwind-app>
