@php($rupiah = fn ($value) => 'Rp '.number_format((float) $value, 0, ',', '.'))
<div class="space-y-6">
    <x-page-header title="Laporan Audit" subtitle="Pilih tab laporan untuk meninjau data secara lebih terarah." kicker="Audit Reporting Suite">
        <x-slot:actions><a href="{{ route('audit-reports.export', 'xlsx') }}" class="ui-btn ui-btn-secondary px-4 py-2.5 text-sm">Unduh XLSX</a><a href="{{ route('audit-reports.export', 'pdf') }}" class="ui-btn ui-btn-primary px-4 py-2.5 text-sm">Cetak PDF</a></x-slot:actions>
        <p class="text-xs font-semibold text-[var(--ui-fg-muted)]">{{ $year->year }} · {{ $fundSource?->name ?? $year->fund_source }} · ID {{ session('active_fund_source_id') }}</p>
        <div class="grid divide-y divide-[var(--ui-line)] sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4"><x-stat-item label="RKAS" :value="$rupiah($summary['budget'])" /><x-stat-item label="BKU Belanja" :value="$rupiah($summary['bku'])" /><x-stat-item label="Transaksi Unik" :value="number_format($summary['transactionCount'], 0, ',', '.')" :hint="$rupiah($summary['transactions'])" /><x-stat-item label="Temuan SPJ" :value="number_format($summary['exceptionCount'], 0, ',', '.')" :hint="$summary['spjNumbered'].' bernomor / '.$summary['spjPackaged'].' paket'" /></div>
    </x-page-header>
    <nav class="grid gap-2 rounded-2xl border border-[var(--ui-line)] bg-[var(--ui-surface-base)] p-2 sm:grid-cols-2 lg:grid-cols-6" aria-label="Tab laporan audit">
        @foreach(['overview' => ['Ringkasan','dashboard'], 'reconciliation' => ['Rekonsiliasi','report'], 'register' => ['Buku Kas','transaction'], 'tax' => ['Pajak','tax'], 'completeness' => ['Kelengkapan SPJ','document'], 'history' => ['Riwayat','sync']] as $key => [$label, $icon])<button type="button" wire:click="setTab('{{ $key }}')" class="ui-btn flex items-center justify-center gap-2 px-3 py-3 text-sm {{ $tab === $key ? 'ui-btn-primary' : 'text-[var(--ui-fg)] hover:bg-[var(--ui-surface-soft)]' }}"><x-ui.icon :name="$icon" size="sm" /><span>{{ $label }}</span></button>@endforeach
    </nav>
    @if($tab === 'overview')
        <div class="grid gap-6 lg:grid-cols-2"><x-ui.alert type="warning" title="Batasan data audit" class="items-start"><ul class="list-disc space-y-2 pl-5 text-sm">@foreach($limitations as $limitation)<li>{{ $limitation }}</li>@endforeach</ul></x-ui.alert><div class="rounded-2xl border border-[var(--ui-line)] bg-[var(--ui-surface-base)] px-5 py-5 shadow-sm"><h2 class="font-bold text-[var(--ui-fg-strong)]">Indikator pemeriksaan</h2><div class="mt-4 grid grid-cols-2 gap-3 text-sm"><x-stat-item label="Selisih rekonsiliasi" :value="$summary['mismatchCount']" /><x-stat-item label="Paket SPJ" :value="$summary['spjPackaged']" /><x-stat-item label="Sinkronisasi" :value="$summary['syncCount']" /><x-stat-item label="Aktivitas audit" :value="$summary['auditCount']" /></div></div></div>
    @elseif($tab === 'reconciliation')
        <x-ui.table min-width="1080px"><thead><tr><th>No Bukti</th><th>Tanggal</th><th class="text-right">RKAS</th><th class="text-right">BKU</th><th class="text-right">Transaksi</th><th class="text-right">Selisih</th><th>SPJ</th><th>Status</th></tr></thead><tbody>@forelse($reconciliationRows as $row)<tr><td class="font-mono font-bold">{{ $row->no_bukti }}</td><td>{{ optional($row->transaction_date)->translatedFormat('d F Y') ?: '-' }}</td><td class="text-right">{{ $rupiah($row->rkas_amount) }}</td><td class="text-right">{{ $rupiah($row->bku_amount) }}</td><td class="text-right">{{ $rupiah($row->transaction_amount) }}</td><td class="text-right">{{ $rupiah($row->variance) }}</td><td>{{ $row->spj_status }}</td><td>{{ $row->status }}</td></tr>@empty<tr><td colspan="8" class="empty-cell">Belum ada data rekonsiliasi.</td></tr>@endforelse</tbody></x-ui.table><x-livewire.audit-pagination :paginator="$reconciliationRows" page-name="reconciliation_page" per-page="reconciliationPerPage" noun="baris rekonsiliasi" />
    @elseif($tab === 'register')
        <x-ui.table min-width="900px"><thead><tr><th>Bukti / Tanggal</th><th>Uraian / Penerima</th><th>Kegiatan / Rekening</th><th class="text-right">Bruto</th><th class="text-right">Pajak</th><th>SPJ</th></tr></thead><tbody>@forelse($register as $transaction)<tr><td><a class="font-mono font-bold" href="{{ route('transactions.show', $transaction->id) }}">{{ $transaction->sourceValue('no_bukti') }}</a><p class="text-xs">{{ $transaction->sourceCarbon()?->translatedFormat('d F Y') ?: '-' }}</p></td><td>{{ $transaction->sourceValue('description') ?: '-' }}<p class="text-xs">{{ $transaction->sourceValue('recipient_name') ?: '-' }}</p></td><td>{{ $transaction->sourceValue('activity_code') ?: '-' }}<p class="text-xs">{{ $transaction->sourceValue('account_code') ?: 'Belum diisi' }}</p></td><td class="text-right">{{ $rupiah($transaction->sourceValue('gross_amount')) }}</td><td class="text-right">{{ $rupiah($transaction->sourceValue('tax_total')) }}</td><td>{{ $transaction->spjPackage?->document_number ?: ($transaction->spjPackage ? 'DRAFT' : 'BELUM ADA') }}</td></tr>@empty<tr><td colspan="6" class="empty-cell">Belum ada transaksi tersinkron.</td></tr>@endforelse</tbody></x-ui.table><x-livewire.audit-pagination :paginator="$register" page-name="register_page" per-page="registerPerPage" noun="transaksi" />
    @elseif($tab === 'tax')
        <x-ui.table><thead><tr><th>Jenis</th><th class="text-right">Transaksi</th><th class="text-right">Nominal</th></tr></thead><tbody>@foreach($taxSummary as $row)<tr><td>{{ $row->label }}</td><td class="text-right">{{ $row->count }}</td><td class="text-right">{{ $rupiah($row->amount) }}</td></tr>@endforeach</tbody></x-ui.table>
    @elseif($tab === 'completeness')
        <x-ui.table min-width="900px"><thead><tr><th>No Bukti</th><th>Tanggal</th><th>Penerima</th><th class="text-right">Bruto</th><th>Status</th><th>Temuan</th></tr></thead><tbody>@forelse($completenessRows as $row)<tr><td>{{ $row->no_bukti }}</td><td>{{ optional($row->transaction_date)->translatedFormat('d F Y') ?: '-' }}</td><td>{{ $row->recipient_name ?: '-' }}</td><td class="text-right">{{ $rupiah($row->amount) }}</td><td>{{ $row->status }}</td><td class="text-xs">{{ $row->issues ? implode('; ', $row->issues) : '-' }}</td></tr>@empty<tr><td colspan="6" class="empty-cell">Tidak ada data pengecualian.</td></tr>@endforelse</tbody></x-ui.table><x-livewire.audit-pagination :paginator="$completenessRows" page-name="completeness_page" per-page="completenessPerPage" noun="baris kelengkapan" />
    @else
        <x-ui.table min-width="780px"><thead><tr><th>Jenis</th><th>Status / Aksi</th><th>Waktu</th><th>Keterangan</th></tr></thead><tbody>@forelse($syncRuns as $row)<tr><td>SINKRONISASI {{ $row->source }}</td><td>{{ $row->status }}</td><td>{{ $row->started_at }}</td><td>{{ $row->message ?: 'Data dibaca: '.$row->records_read.' · ditulis: '.$row->records_written }}</td></tr>@empty<tr><td colspan="4" class="empty-cell">Belum ada riwayat sinkronisasi.</td></tr>@endforelse @foreach($auditLogs as $row)<tr><td>{{ $row->entity_type }}</td><td>{{ $row->action }}</td><td>{{ $row->created_at }}</td><td>{{ $row->description }}</td></tr>@endforeach</tbody></x-ui.table><x-livewire.audit-pagination :paginator="$syncRuns" page-name="history_page" per-page="historyPerPage" noun="sinkronisasi" />
    @endif
</div>
