<div>
    <div class="flex flex-wrap items-end justify-between gap-3 border-b border-[var(--ui-line)] bg-[var(--ui-surface-soft)] px-5 py-4">
        <div><h2 class="font-bold text-[var(--ui-fg-strong)]">Transaksi {{ $isHonor ? 'Honor Pegawai' : 'Jasa Lainnya' }}</h2><p class="mt-1 text-xs text-[var(--ui-fg-muted)]">Pilih satu atau beberapa transaksi untuk disusun menjadi laporan penerima pembayaran.</p></div>
        <div class="flex flex-wrap gap-2"><x-ui.button type="button" variant="secondary" class="!min-h-8 !px-2 !py-1 text-xs" wire:click="selectAll">Pilih Semua</x-ui.button><x-ui.button type="button" variant="secondary" class="!min-h-8 !px-2 !py-1 text-xs" wire:click="clearSelection">Bersihkan</x-ui.button><x-ui.button type="button" class="!min-h-8 !px-2 !py-1 text-xs" wire:click="continueToCompose" icon="arrow-right">Lanjutkan</x-ui.button></div>
    </div>
    <div class="grid gap-3 border-b border-[var(--ui-line)] px-5 py-4 sm:grid-cols-3">
        <x-ui.field label="Bulan" for="report-month"><x-ui.select id="report-month" wire:model.live="month"><option value="">Semua bulan</option>@foreach(['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'] as $index => $label)<option value="{{ $index + 1 }}">{{ $label }}</option>@endforeach</x-ui.select></x-ui.field>
        <x-ui.field label="Triwulan" for="report-quarter"><x-ui.select id="report-quarter" wire:model.live="quarter"><option value="">Semua triwulan</option>@foreach(range(1,4) as $item)<option value="{{ $item }}">Triwulan {{ $item }}</option>@endforeach</x-ui.select></x-ui.field>
        <x-ui.field label="Semester" for="report-semester"><x-ui.select id="report-semester" wire:model.live="semester"><option value="">Semua semester</option><option value="1">Semester I</option><option value="2">Semester II</option></x-ui.select></x-ui.field>
    </div>
    @error('selected')<x-ui.alert type="danger" class="mx-5 mt-4">{{ $message }}</x-ui.alert>@enderror
    <div class="overflow-x-auto p-5"><table class="min-w-full divide-y divide-[var(--ui-line)] text-sm"><thead class="bg-[var(--ui-surface-soft)]"><tr><th class="px-3 py-3 text-center">Pilih</th><th class="px-3 py-3 text-left">BPU / Tanggal</th><th class="px-3 py-3 text-left">Uraian / Penerima</th><th class="px-3 py-3 text-left">Periode</th><th class="px-3 py-3 text-right">Bruto</th><th class="px-3 py-3 text-right">Dibayarkan</th></tr></thead><tbody class="divide-y divide-[var(--ui-line)]">
        @forelse($transactions as $transaction)<tr wire:key="report-transaction-{{ $transaction->id }}" class="hover:bg-[var(--ui-surface-soft)]"><td class="px-3 py-4 text-center"><input type="checkbox" wire:model="selected" value="{{ $transaction->id }}" class="h-4 w-4 rounded border-[var(--ui-line-strong)]"></td><td class="px-3 py-4"><div class="font-mono font-bold text-[var(--theme-content-accent)]">{{ $transaction->sourceValue('no_bukti') }}</div><div class="text-xs text-[var(--ui-fg-muted)]">{{ $transaction->sourceCarbon()?->translatedFormat('d F Y') ?: '-' }}</div></td><td class="px-3 py-4"><div class="font-semibold text-[var(--ui-fg)]">{{ $transaction->payment_description ?: $transaction->sourceValue('description') }}</div><div class="mt-1 text-xs text-[var(--ui-fg-muted)]">{{ $isHonor ? ($transaction->honors->pluck('name')->filter()->unique()->implode(', ') ?: $transaction->sourceValue('recipient_name')) : $transaction->serviceRecipients->pluck('name')->filter()->unique()->implode(', ') }}</div></td><td class="px-3 py-4">{{ $transaction->sourceCarbon()?->translatedFormat('F Y') ?: '-' }}</td><td class="px-3 py-4 text-right">{{ number_format((float) $transaction->sourceValue('gross_amount'), 0, ',', '.') }}</td><td class="px-3 py-4 text-right font-bold">{{ number_format((float) $transaction->sourceValue('net_amount'), 0, ',', '.') }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-[var(--ui-fg-muted)]">Belum ada transaksi {{ $isHonor ? 'Honor Pegawai' : 'Jasa Lainnya' }} yang memiliki rincian penerima.</td></tr>@endforelse
    </tbody></table></div>
    <div class="border-t border-[var(--ui-line)] px-5 py-3 text-xs text-[var(--ui-fg-muted)]">{{ count($selected) }} transaksi dipilih.</div>
</div>
